#ifndef PRAGMA_ASYNCIO_LIB_H
#define PRAGMA_ASYNCIO_LIB_H

/*
** Aztec 'C', Maxon 'C' and StormC format pragma files
**
**
** Generated by LibDescConverter from an sfd file
*/

#ifndef CLIB_ASYNCIO_PROTOS_H
#include <clib/asyncio_protos.h>
#endif /* CLIB_ASYNCIO_PROTOS_H */

/* "asyncio.library" */
#pragma amicall(AsyncIOBase, 0x1E, OpenAsync(a0,d0,d1))
#pragma amicall(AsyncIOBase, 0x24, OpenAsyncFromFH(a0,d0,d1))
#pragma amicall(AsyncIOBase, 0x2A, CloseAsync(a0))
#pragma amicall(AsyncIOBase, 0x30, SeekAsync(a0,d0,d1))
#pragma amicall(AsyncIOBase, 0x36, ReadAsync(a0,a1,d0))
#pragma amicall(AsyncIOBase, 0x3C, WriteAsync(a0,a1,d0))
#pragma amicall(AsyncIOBase, 0x42, ReadCharAsync(a0))
#pragma amicall(AsyncIOBase, 0x48, WriteCharAsync(a0,d0))
#pragma amicall(AsyncIOBase, 0x4E, ReadLineAsync(a0,a1,d0))
#pragma amicall(AsyncIOBase, 0x54, WriteLineAsync(a0,a1))
#pragma amicall(AsyncIOBase, 0x5A, FGetsAsync(a0,a1,d0))
#pragma amicall(AsyncIOBase, 0x60, FGetsLenAsync(a0,a1,d0,a2))
#pragma amicall(AsyncIOBase, 0x66, PeekAsync(a0,a1,d0))

#endif /* PRAGMA_ASYNCIO_LIB_H */
