#ifndef CLIB_ASYNCIO_PROTOS_H
#define CLIB_ASYNCIO_PROTOS_H

/*
** 'C' prototypes. For use with 32 bit integers only.
**
**
** Generated by LibDescConverter from an sfd file
*/

#ifdef __cplusplus
extern "C" {
#endif /* __cplusplus */

#ifndef LIBRARIES_ASYNCIO_H
#include <libraries/asyncio.h>
#endif

/* "asyncio.library"*/
struct AsyncFile *OpenAsync(STRPTR fileName, ULONG mode, LONG bufferSize);
struct AsyncFile *OpenAsyncFromFH(BPTR handle, ULONG mode, LONG bufferSize);
LONG CloseAsync(struct AsyncFile *file);
LONG SeekAsync(struct AsyncFile *file, LONG position, LONG mode);
LONG ReadAsync(struct AsyncFile *file, APTR buffer, LONG bytes);
LONG WriteAsync(struct AsyncFile *file, APTR buffer, LONG bytes);
LONG ReadCharAsync(struct AsyncFile *file);
LONG WriteCharAsync(struct AsyncFile *file, ULONG ch);
LONG ReadLineAsync(struct AsyncFile *file, STRPTR buf, LONG bytes);
LONG WriteLineAsync(struct AsyncFile *file, STRPTR buf);
STRPTR FGetsAsync(struct AsyncFile *file, STRPTR buf, LONG bytes);
STRPTR FGetsLenAsync(struct AsyncFile *file, STRPTR buf, LONG bytes, LONG *length);
LONG PeekAsync(struct AsyncFile *file, APTR buffer, LONG bytes);

#ifdef __cplusplus
}
#endif /* __cplusplus */

#endif /* CLIB_ASYNCIO_PROTOS_H */
