#ifndef INLINE_ASYNCIO_PROTOS_H
#define INLINE_ASYNCIO_PROTOS_H

/*
** VBCC format inline files.
**
**
** Generated by LibDescConverter from an sfd file
*/

/* "asyncio.library" */
struct AsyncFile *__OpenAsync(__reg("a6") void *, __reg("a0") STRPTR fileName, __reg("d0") ULONG mode, __reg("d1") LONG bufferSize)="\tjsr\t-30(a6)";
#define OpenAsync(fileName, mode, bufferSize) __OpenAsync(AsyncIOBase, (fileName), (mode), (bufferSize))

struct AsyncFile *__OpenAsyncFromFH(__reg("a6") void *, __reg("a0") BPTR handle, __reg("d0") ULONG mode, __reg("d1") LONG bufferSize)="\tjsr\t-36(a6)";
#define OpenAsyncFromFH(handle, mode, bufferSize) __OpenAsyncFromFH(AsyncIOBase, (handle), (mode), (bufferSize))

LONG __CloseAsync(__reg("a6") void *, __reg("a0") struct AsyncFile *file)="\tjsr\t-42(a6)";
#define CloseAsync(file) __CloseAsync(AsyncIOBase, (file))

LONG __SeekAsync(__reg("a6") void *, __reg("a0") struct AsyncFile *file, __reg("d0") LONG position, __reg("d1") LONG mode)="\tjsr\t-48(a6)";
#define SeekAsync(file, position, mode) __SeekAsync(AsyncIOBase, (file), (position), (mode))

LONG __ReadAsync(__reg("a6") void *, __reg("a0") struct AsyncFile *file, __reg("a1") APTR buffer, __reg("d0") LONG bytes)="\tjsr\t-54(a6)";
#define ReadAsync(file, buffer, bytes) __ReadAsync(AsyncIOBase, (file), (buffer), (bytes))

LONG __WriteAsync(__reg("a6") void *, __reg("a0") struct AsyncFile *file, __reg("a1") APTR buffer, __reg("d0") LONG bytes)="\tjsr\t-60(a6)";
#define WriteAsync(file, buffer, bytes) __WriteAsync(AsyncIOBase, (file), (buffer), (bytes))

LONG __ReadCharAsync(__reg("a6") void *, __reg("a0") struct AsyncFile *file)="\tjsr\t-66(a6)";
#define ReadCharAsync(file) __ReadCharAsync(AsyncIOBase, (file))

LONG __WriteCharAsync(__reg("a6") void *, __reg("a0") struct AsyncFile *file, __reg("d0") ULONG ch)="\tjsr\t-72(a6)";
#define WriteCharAsync(file, ch) __WriteCharAsync(AsyncIOBase, (file), (ch))

LONG __ReadLineAsync(__reg("a6") void *, __reg("a0") struct AsyncFile *file, __reg("a1") STRPTR buf, __reg("d0") LONG bytes)="\tjsr\t-78(a6)";
#define ReadLineAsync(file, buf, bytes) __ReadLineAsync(AsyncIOBase, (file), (buf), (bytes))

LONG __WriteLineAsync(__reg("a6") void *, __reg("a0") struct AsyncFile *file, __reg("a1") STRPTR buf)="\tjsr\t-84(a6)";
#define WriteLineAsync(file, buf) __WriteLineAsync(AsyncIOBase, (file), (buf))

STRPTR __FGetsAsync(__reg("a6") void *, __reg("a0") struct AsyncFile *file, __reg("a1") STRPTR buf, __reg("d0") LONG bytes)="\tjsr\t-90(a6)";
#define FGetsAsync(file, buf, bytes) __FGetsAsync(AsyncIOBase, (file), (buf), (bytes))

STRPTR __FGetsLenAsync(__reg("a6") void *, __reg("a0") struct AsyncFile *file, __reg("a1") STRPTR buf, __reg("d0") LONG bytes, __reg("a2") LONG *length)="\tjsr\t-96(a6)";
#define FGetsLenAsync(file, buf, bytes, length) __FGetsLenAsync(AsyncIOBase, (file), (buf), (bytes), (length))

LONG __PeekAsync(__reg("a6") void *, __reg("a0") struct AsyncFile *file, __reg("a1") APTR buffer, __reg("d0") LONG bytes)="\tjsr\t-102(a6)";
#define PeekAsync(file, buffer, bytes) __PeekAsync(AsyncIOBase, (file), (buffer), (bytes))


#endif /* INLINE_ASYNCIO_PROTOS_H */
